### ISSUE TITLE
Use AJAX to send Form Data

### ISSUE THREAD

**Issue by c-schwarze** [betheluniversity/directory#10]
If we use AJAX, then we won't have to load the entire page again. We will only load the data that is being changed.

I also think this will fix the fields from clearing themselves out

**Comment by johjacb** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/FormData/FormData

Right now, the form is using the Form Data object to send the data via AJAX. But it's being force-fed by appending specific fields. Can we work it out to simply send the form as a whole?

`var formData = new FormData(form)` 

vs 

`var formData = new FormData()
formData.append('first_name', form.querySelector("#first_name").value)`

this should give us more flexibility and less code to maintain

**Comment by johjacb** [comment]
updated to use FormData
