### ISSUE TITLE
Department Search autocomplete

### ISSUE THREAD

**Issue by bak45247** [betheluniversity/directory#12]
Writing a dept search in the directory

- Shows staff and faculty
- Same stuff as student
- Plus: dept, ext, job title, office #

**Comment by johjacb** [comment]
Need help getting the autocomplete working

**Comment by johjacb** [comment]
Using this plain JS option:

https://leaverou.github.io/awesomplete/#api

**Comment by bak45247** [comment]
Need to reconnect database to the autocomplete box

**Comment by johjacb** [comment]
is the data updated regularly? if not, we could put a list of the departments as an array in the JS.

**Comment by bak45247** [comment]
that would be a question for Derek, I don't know how/when thats updated. I just connected that db to my Jinja before

**Comment by c-schwarze** [comment]
Yeah the data gets updated every so often - a few times a year at least. I think it makes sense to pull the data instead of manage it ourselves.

**Comment by johjacb** [comment]
can you help get that connected with Awesomplete? link above ^

**Comment by c-schwarze** [comment]
Yep. I just merged the update into master. Its a bit ugly, since the code lives in 2 places - but it'll work.
