### ISSUE TITLE
Something to signify exact match

### ISSUE THREAD

**Issue by bak45247** [betheluniversity/directory#30]
Some kind of visual to signify an exact match between results and search terms

**Comment by c-schwarze** [comment]
In our web meeting, we talked about maybe displaying the field(s) that were searched for on the card, without clicking into a person's data.

**Comment by c-schwarze** [comment]
I connected the fields. Passing off to Jake to add design as needed.

**Comment by c-schwarze** [comment]
We decided to move away from signifying exact/partial matches due to the limited use case. There are many complicated cases that limit the potential of exact matches.
