### ISSUE TITLE
Database incomplete

### ISSUE THREAD

**Issue by bak45247** [betheluniversity/directory#31]
The database isn't grabbing all of the students, limiting search results to the ones retrieved.

I don't know how to fix this. But thats why our results are returning less than we expect

**Comment by bak45247** [comment]
For example, Grant and Bailey both won't show up in any searches, even if you search their full names

**Comment by c-schwarze** [comment]
This is expected, since we are using banqual. banqual's data is older, so we have limited results. This will not be an issue on prod
