### ISSUE TITLE
Combination Searches

### ISSUE THREAD

**Issue by c-schwarze** [betheluniversity/directory#35]
With the new form Jake made, we need to capacity to make combination searches. This means that we should be able to combine FN/LN search with any of the other searches. But not the other searches with each other.

**Comment by c-schwarze** [comment]
Looks like this is being worked on in the `search-box-logic` branch

**Comment by johjacb** [comment]
Logic will now be broken out in to:
Name
Department
Name + Department 

Or 1 of:
Username
ID
Email

**Comment by bak45247** [comment]
If someone could look over this for potential errors that would be great. Also, this depends on connecting to the db for departments. So, if we could get that done, that would also be great.
