### ISSUE TITLE
Top right menu

### ISSUE THREAD

**Issue by c-schwarze** [betheluniversity/directory#36]
We want to have the top right menu appear the same as MyBethel

**Comment by johjacb** [comment]
html has been updated

**Comment by c-schwarze** [comment]
@johjacb Currently the top right menu on master branch doesn't have an image. Is that intentional?

**Comment by johjacb** [comment]
directory/app/templates/modules/navbar.html
     
If you look here, I've got the html in place, but I don't think the logic is right

**Comment by c-schwarze** [comment]
Ah, gotcha. Thanks!

@bak45247 want to work on hooking this up?

**Comment by c-schwarze** [comment]
I went ahead and connected this
