### ISSUE TITLE
Searches fail when you are signed out of CAS

### ISSUE THREAD

**Issue by c-schwarze** [betheluniversity/directory#43]
If someone leaves their browser open for extended periods of time, the search will not work. The issue is we use ajax, so ajax is getting the CAS page instead of the search results. We should update our ajax to "error" properly. Maybe just send to the homepage

**Comment by c-schwarze** [comment]
Since we are using asynchronous calls, we actually can't do this. https://bytearcher.com/articles/why-asynchronous-exceptions-are-uncatchable/

If we think this is an issue, we will have to remove the ajax portion of the searches, which seems decent.

**Comment by c-schwarze** [comment]
Actually, this can be done! https://stackoverflow.com/questions/22099706/handling-ajax-error-native-js

**Comment by johjacb** [comment]
Do we actually want to allow people to search when sign out?

**Comment by c-schwarze** [comment]
Well the issue is there wasn't a prompt. A user could log in, then have their session time out, then try to search. But when they search, nothing would happen on the screen.

**Comment by johjacb** [comment]
Ah got it. I thought they got force out of their session

**Comment by c-schwarze** [comment]
They do, but because we don't refresh the page and we are using AJAX, we needed to handle this specifically
