### ISSUE TITLE
Test infinite scroll & add animation

### ISSUE THREAD

**Issue by c-schwarze** [betheluniversity/directory#48]
Loading 100+ images can be costly - especially for mobile. Lets limit the search results to 20 and load more as the users needs it (infinite scroll).

https://codepen.io/wernight/details/YyvNoW

We will need to do an AJAX call everytime the user needs more.

**Comment by c-schwarze** [comment]
@johjacb is going to add that package

@c-schwarze is going to add the logic to pull the next 20

**Comment by johjacb** [comment]
functionality is in place, need to test all browsers

**Comment by c-schwarze** [comment]
When testing with slow speeds, I think there is an apparent need to display the loading GIF.

**Comment by johjacb** [comment]
i'll look into it

**Comment by johjacb** [comment]
ok the loading animation has been updated. need to test all browsers now

**Comment by johjacb** [comment]
tested and working
