### ISSUE TITLE
Department Search bug when pushing enter

### ISSUE THREAD

**Issue by c-schwarze** [betheluniversity/directory#73]
If you don't click on the results from the department search, then the search fails. Lets try to write some fancy JS code to make pushing the enter, when you have the department text field highlighted, select the first result.

**Comment by johjacb** [comment]
https://leaverou.github.io/awesomplete/#events

**Comment by c-schwarze** [comment]
I read through that. I'm not sure what you are thinking

**Comment by johjacb** [comment]
I didn't come up with a plan yet, just thought that would be a good place to start

**Comment by johjacb** [comment]
found an option 'autoFirst' which auto highlights the first item in the dropdown. So if you start typing 'edu', 'Education' will be highlighted. if you hit return, it fills in the field. You have to hit return again to search. I wonder if this helps?

i pushed the change out

**Comment by c-schwarze** [comment]
That sounds like a good option. I think it will be pretty intuitive. Thanks Jake!

**Comment by c-schwarze** [comment]
This change isn't working for me. When I enter "mark" into the department and push enter, it just does a search for "mark", which fails.

I tried in both Chrome and Firefox

**Comment by c-schwarze** [comment]
The code wasn't pulled when I tested. It works great
