### ISSUE TITLE
Move the home/ID information out of the extra text dropdown

### ISSUE THREAD

**Issue by c-schwarze** [betheluniversity/directory#75]
@johjacb can you work with Tim on this and come to a decision?

**Comment by johjacb** [comment]
Per our conversation, the plan is to make the 'Home details' link more visible

**Comment by c-schwarze** [comment]
I see the update you made to make it appear more like a button. Should this be added to the "show ID" portion as well?

**Comment by johjacb** [comment]
we definitely could...i didn't initially because it seems like such a small percentage of people will be using it that I didn't want it to compete with the other button. but i'm fine either way

**Comment by c-schwarze** [comment]
I'm fine leaving it as is, if you feel good about the design.

**Comment by johjacb** [comment]
We can let Tim make the final call!

**Comment by johjacb** [comment]
new plan is to not hide any info

**Comment by johjacb** [comment]
all info is shown now

closing
