### ISSUE TITLE
remove <b> elements

### ISSUE THREAD

**Issue by josiahtillman** [betheluniversity/directory#98]
"The `<b>` element is used to draw attention to enclosed text without implying any added importance or emphasis. Text surrounded by `<b>` tags is displayed with a bold typeface." 
— https://html.com/tags/b/

We should be using the bootstrap class `font-weight-bold` or just using the `<strong>` tag instead

**Comment by c-schwarze** [comment]
@mjweiberg28 this should be a good one to start on. Bailey should be a good resource to help you get your env for the directory setup. Once you get the directory setup and able to search, go ahead and start on this issue. 

As always, reach out if you have any questions or issues.
